DROP INDEX PK_REGIONAL_COUNT;

/* 지역별현황정보 */
DROP TABLE REGIONAL_COUNT 
  CASCADE CONSTRAINTS;

/* 지역별현황정보 */
CREATE TABLE REGIONAL_COUNT (
  GANGWON VARCHAR2(50), /* 강원 */
  GYEONGGI VARCHAR2(50), /* 경기 */
  GYEONGNAM VARCHAR2(50), /* 경남 */
  GYEONGBUK VARCHAR2(50), /* 경북 */
  GWANGJU VARCHAR2(50), /* 광주 */
    STANDARD_DATE VARCHAR2(50) NOT NULL, /* 기준일 */
  DAEGU VARCHAR2(50), /* 대구 */
  DAEJEON VARCHAR2(50), /* 대전 */
  BUSAN VARCHAR2(50), /* 부산 */
  SEOUL VARCHAR2(50), /* 서울 */
  SEJONG VARCHAR2(50), /* 세종 */
  ULSAN VARCHAR2(50), /* 울산 */
  INCHEON VARCHAR2(50), /* 인천 */
  JEONNAM VARCHAR2(50), /* 전남 */
  JEONBUK VARCHAR2(50), /* 전북 */
  JEJU VARCHAR2(50), /* 제주 */
  CHOONGNAM VARCHAR2(50), /* 충남 */
  CHOONGBUK VARCHAR2(50), /* 충북 */
  COUNT_SUM VARCHAR2(50) /* 합계 */
);

COMMENT ON TABLE REGIONAL_COUNT IS '지역별현황정보';

COMMENT ON COLUMN REGIONAL_COUNT.STANDARD_DATE IS '기준일';

COMMENT ON COLUMN REGIONAL_COUNT.GANGWON IS '강원';

COMMENT ON COLUMN REGIONAL_COUNT.GYEONGGI IS '경기';

COMMENT ON COLUMN REGIONAL_COUNT.GYEONGNAM IS '경남';

COMMENT ON COLUMN REGIONAL_COUNT.GYEONGBUK IS '경북';

COMMENT ON COLUMN REGIONAL_COUNT.GWANGJU IS '광주';

COMMENT ON COLUMN REGIONAL_COUNT.DAEGU IS '대구';

COMMENT ON COLUMN REGIONAL_COUNT.DAEJEON IS '대전';

COMMENT ON COLUMN REGIONAL_COUNT.BUSAN IS '부산';

COMMENT ON COLUMN REGIONAL_COUNT.SEOUL IS '서울';

COMMENT ON COLUMN REGIONAL_COUNT.SEJONG IS '세종';

COMMENT ON COLUMN REGIONAL_COUNT.ULSAN IS '울산';

COMMENT ON COLUMN REGIONAL_COUNT.INCHEON IS '인천';

COMMENT ON COLUMN REGIONAL_COUNT.JEONNAM IS '전남';

COMMENT ON COLUMN REGIONAL_COUNT.JEONBUK IS '전북';

COMMENT ON COLUMN REGIONAL_COUNT.JEJU IS '제주';

COMMENT ON COLUMN REGIONAL_COUNT.CHOONGNAM IS '충남';

COMMENT ON COLUMN REGIONAL_COUNT.CHOONGBUK IS '충북';

COMMENT ON COLUMN REGIONAL_COUNT.COUNT_SUM IS '합계';

CREATE UNIQUE INDEX PK_REGIONAL_COUNT
  ON REGIONAL_COUNT (
    STANDARD_DATE ASC
  );

ALTER TABLE REGIONAL_COUNT
  ADD
    CONSTRAINT PK_REGIONAL_COUNT
    PRIMARY KEY (
      STANDARD_DATE
    );