DROP INDEX PK_STATION_DATA;

/* 충전소정보 */
DROP TABLE STATION_DATA 
  CASCADE CONSTRAINTS;

/* 충전소정보 */
CREATE TABLE STATION_DATA (
  STATION_SEQ NUMBER(10), /* 순번 */
  ADDR VARCHAR2(200), /* 주소 */
  CHARGETP VARCHAR2(100), /* 충전기타입 */
  CPID NUMBER(10), /* 충전기ID */
  CPNM VARCHAR2(20), /* 충전기명칭 */
  CPSTAT VARCHAR2(100), /* 충전기상태 */
  CPTP VARCHAR2(100), /* 충전방식 */
  CSID NUMBER(10), /* 충전소ID */
  CSNM VARCHAR2(100), /* 충전소명칭 */
  LAT VARCHAR2(50), /* 위도 */
  LONGI VARCHAR2(50), /* 경도 */
  STATUPDATETIME VARCHAR2(100) /* 갱신시간 */
);

COMMENT ON TABLE STATION_DATA IS '충전소정보';

COMMENT ON COLUMN STATION_DATA.ADDR IS '주소';

COMMENT ON COLUMN STATION_DATA.CHARGETP IS '충전기타입';

COMMENT ON COLUMN STATION_DATA.CPID IS '충전기ID';

COMMENT ON COLUMN STATION_DATA.CPNM IS '충전기명칭';

COMMENT ON COLUMN STATION_DATA.CPSTAT IS '충전기상태';

COMMENT ON COLUMN STATION_DATA.CPTP IS '충전방식';

COMMENT ON COLUMN STATION_DATA.CSID IS '충전소ID';

COMMENT ON COLUMN STATION_DATA.CSNM IS '충전소명칭';

COMMENT ON COLUMN STATION_DATA.LAT IS '위도';

COMMENT ON COLUMN STATION_DATA.LONGI IS '경도';

COMMENT ON COLUMN STATION_DATA.STATUPDATETIME IS '갱신시간';

CREATE UNIQUE INDEX PK_STATION_DATA
  ON STATION_DATA (
    STATION_SEQ ASC
  );

ALTER TABLE STATION_DATA
  ADD
    CONSTRAINT PK_STATION_DATA
    PRIMARY KEY (
      STATION_SEQ
    );






--SEQ 삭제
DROP SEQUENCE STATION_SEQ;
        
--SEQ 생성
CREATE SEQUENCE  "STATION_SEQ"  
 MINVALUE 1 
 MAXVALUE 99999999
 INCREMENT BY 1 
 START WITH 1 
 CACHE 20 
 NOORDER  
 NOCYCLE  
 NOKEEP  
 NOSCALE  
 GLOBAL ;
 
 
 
 
 
 
 -- 결과 확인
SELECT COUNT(*) AS CNT
FROM STATION_DATA;

-- 전체 조회
SELECT *
FROM STATION_DATA
ORDER BY STATION_SEQ ASC;
